version: 2
jobs:
  build:
    docker:
      - image: node:8
    environment:
      TZ: "Asia/Taipei"
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      # Run DETT
      - restore_cache:
          name: DETT - Restore Yarn Package Cache
          keys:
            - DETT-yarn-packages-r3-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - DETT-yarn-packages-r3-{{ .Branch }}-
            - DETT-yarn-packages-r3-
      - run:
          name: DETT - Install Dependencies
          command: yarn install --ignore-scripts --frozen-lockfile
      - save_cache:
          name: DETT - Save Yarn Package Cache
          key: DETT-yarn-packages-r3-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: DETT - Build
          command: npm run build

      # Run DETT_Cache
      - restore_cache:
          name: DETT_Cache - Restore Yarn Package Cache
          keys:
            - DETT_Cache-yarn-packages-r2-{{ .Branch }}-{{ checksum "./DETT_Cache/yarn.lock" }}
            - DETT_Cache-yarn-packages-r2-{{ .Branch }}-
            - DETT_Cache-yarn-packages-r2-
      - run:
          name: DETT_Cache - Install Dependencies
          command: cd ./DETT_Cache; yarn install --frozen-lockfile
      - save_cache:
          name: DETT_Cache - Save Yarn Package Cache
          key: DETT_Cache-yarn-packages-r2-{{ .Branch }}-{{ checksum "./DETT_Cache/yarn.lock" }}
          paths:
            - ./DETT_Cache/node_modules
      - run:
          name: DETT_Cache - Cache
          command: |
            cd ./DETT_Cache
            npm run cache
      - restore_cache:
          name: DETT_Cache - Restore dist Cache
          keys:
            - DETT_Cache-dist-cache-r15-{{ .Branch }}-{{ checksum "./DETT_Cache/dist/output.json" }}
            - DETT_Cache-dist-cache-r15-{{ .Branch }}-
            - DETT_Cache-dist-cache-r15-
      - run:
          name: DETT_Cache - Build-Cache
          command: |
            cd ./DETT_Cache
            ln -s ../build gh-pages
            npm run build-cache
            cp -R ./dist/s gh-pages/
            cp ./dist/sitemap.xml gh-pages/
      - save_cache:
          name: DETT_Cache - Save dist Cache
          key: DETT_Cache-dist-cache-r15-{{ .Branch }}-{{ checksum "./DETT_Cache/dist/output.json" }}
          paths:
            - ./DETT_Cache/dist
      - deploy:
          name: Deploy to branch gh-pages with "gh-pages" tool
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            npm run deploy-ci
      - run:
          name: Cloudflare Purge Cache
          command: npm run cloudflare-purge-cache

workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
